name: Upload To Jcenter

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deploy:
    if: github.repository == 'XueMoMo/CSLayout'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run Gradle command
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: install
            | bintrayUpload